name: Develop
on:
  pull_request:

jobs:
  valid:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@master
    - uses: ./
      with:
        path: ./testdata/ValidProject
        debug: true
  auto_fix:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@master
    - uses: ./
      with:
        path: ./testdata/InvalidProject
        debug: true
        auto_fix: true
        dry_run: true
